import joi from 'joi'

export const email = joi.string().email({ minDomainSegments: 2, tlds: { allow: ['com'] } }).required()
export const password = joi.string().pattern(new RegExp('^[a-zA-Z0-9]{8,30}$')).required()
export const username = joi.string().pattern(new RegExp('^[a-zA-Z0-9]{3,30}$')).required()
export const id = joi.string().pattern(new RegExp('^[a-zA-Z0-9]{3,30}$')).required()
export const Title = joi.string().required()
export const Description = joi.string().required()
export const Artist = joi.string().required()
export const name = joi.string().required()
export const musicUrl = joi.string().required()
export const imageUrl = joi.string().required()
export const visualUrl = joi.string().required()
export const soundUrl = joi.string().required()
export const soundVol = joi.string().required()